name: "Automated API and E2E tests"

on: push

jobs:
  # api-tests:
  #   runs-on: ubuntu-latest
  #   container: mcr.microsoft.com/playwright:v1.42.1-jammy
  #   steps:
  #     - name : "Checkout to tests repository"
  #       uses: actions/checkout@v4
  #       with:
  #        repository: ${{github.repository}}
  #        ref: ${{github.ref}}
  #     - name: "Copy env variables"
  #       run: |
  #         cp '.env.example' '.env'
  #     - name: "Install node.js"
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: "Install dependencies"
  #       run: npm ci
  #     - name: "Run tests"
  #       env:
  #         BASE_URL: 'https://qauto.forstudy.space/'
  #         API_URL: 'https://api.qauto.forstudy.space/'
  #         HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
  #         HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
  #       run: npm run test:api
  #     - name: "Upload report to artifacts"
  #       if: failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: api-tests-report
  #         path: playwright-report/
  #         retention-days: 3

  e2e-tests:
    runs-on: ubuntu-latest
    # needs: [api-tests]
    container: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - name : "Checkout to tests repository"
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          ref: ${{github.ref}}
      - name: "Copy env variables"
        run: |
          cp '.env.example' '.env'
      - name: "Install node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install dependencies"
        run: npm ci
      - name: "Generate Screenshots"
        env:
          BASE_URL: 'https://qauto.forstudy.space/'
          API_URL: 'https://api.qauto.forstudy.space/'
          HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
          HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
        run: npx playwright test --update-snapshots
      - name: "Run tests"
        env:
          BASE_URL: 'https://qauto.forstudy.space/'
          API_URL: 'https://api.qauto.forstudy.space/'
          HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
          HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
        run: npm test
      - name: "Upload report to artifacts"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-report
          path: playwright-report/
          retention-days: 3